### ISSUE TITLE
BigTiff support?

### ISSUE THREAD

**Issue by HagaiHargil** [image-rs/image-tiff#3]
Hi,

I was considering contributing BigTiff support (decoding, for now) to the library. Since I'm nowhere near a Rust expert, I'm still debating with myself on the implementation, since the (BigTiff spec)[https://www.awaresystems.be/imaging/tiff/bigtiff.html] differs from the Tiff spec in several key ways. 

For example, the third byte is always 43, as opposed to Tiff's always 42. This might limit the reuseability of the current `Decoder`, forcing me to re-write large portions of it, essentially creating a `BigTiffRecorder`. On the other hand, the user shouldn't care if the Tiff is a BigTiff or a normal one, he just wants it decoded.

How would you suggest me to tackle this?

**Comment by jansol** [comment]
Hi,

welcome to the Rust world. Don't worry about your skills, PR feedback is there for improving them (and making sure nothing too terrible gets merged without fixing it first, of course).

As for the code architecture, the byte you mention seems to be just a marker in the magic header right at the beginning of the file. As such it probably makes sense to have two separate `Decoder`s internally, but I'd keep the public interface to just one. You could have a private field of type `enum {Tiff(Decoder), BigTiff(BigDecoder)}` and have the public API switch based on that when you really need completely different behavior for the two.

**Comment by Farkal** [comment]
This should be fixed by #83 (waiting for the release to close this issue)

**Comment by HeroicKatora** [comment]
Previous comment suggests this is closed. If this is wrong, feel free to reopen.

**Comment by phil-opp** [comment]
It looks like only decoding is supported for BigTiff, is that right? Are there any plans to add encoding support too?

**Comment by Farkal** [comment]
If you plan to do it yes there is 😄 
I have no more time allocated to tiff improvement at work 😞 but my schemes can help you to implement it  -> https://github.com/image-rs/image-tiff/issues/47

**Comment by phil-opp** [comment]
Thanks for the quick reply! Your schemes look indeed useful.

(I don't know if I'll be able to work on this though, we are still not sure whether we need BigTiff support at all.)
